Review
Janis1992-08/Capstone-Project-ServiceCircle pull request #32
Opened 2024-01-10 09:49 UTC by AmjedXKhattab

2024-01-10 11:05 UTC, mbosselmann reviewed
Hi Team ServiceCircle,
good job! 💪 
But I have some remarks regarding the implementation of the feature. As we just talked about the handling of the star rating and I think the handling of the data could be solved the same way, please check and ask me if anything is unclear. :)

2024-01-10 11:30 UTC, AmjedXKhattab commented on components/ServiceProvider/index.js
> +
> ```js
>   useEffect(() => {
>     const storedReviews = localStorage.getItem(`reviews_${card.id}`);
>     if (storedReviews) {
>       setReviews(JSON.parse(storedReviews));
>     }
>   }, [card.id]);
> 
>   const addReview = (cardId, review) => {
>     const updatedReviews = { ...reviews, [cardId]: review };
>     setReviews(updatedReviews);
>     localStorage.setItem(`reviews_${card.id}`, JSON.stringify(updatedReviews));
>   };
> ```
> 
> This part need to be updated then too and moved to the `_app.js` too (the `useEffect` won't be necessary anymore then). You have two states in your `_app.js`:
> 
> ```js
>   const [serviceCards, setServiceCards] = useLocalStorageState("serviceCards", {
>     defaultValue: [],
>   });
>   const [favorites, setFavorites] = useLocalStorageState("favorites", {
>     defaultValue: [],
>   });
> ```
> 
> It is up to you to decide if you want to add the review to the serviceCards state (like you just did for the star rating) or if you want to create a new state and handle the adding of review like the `favorites`. :)
> 
> The `handleAddReview` function then needs to update the state from your choice. Currently the user can also only add one review and not multiple reviews (the last one will be overwritten). It this really intended as the user is not hindered in submitting a new review? :)
> 
> And for the `localStorage`: Currently you would create for each service card a new `localStorage` entry. This can be really confusing if you have multiple services. A better way to store reviews would be to have one `reviews` array with objects like `{id: <cardid>, review: "my review!"}`. The `review` key could also be an array if you want to store multiple reviews for one service. If the reviews should be part of the `serviceCards` state then you do not need an extra local storage entry.

@mbosselmann 
Thank you for the review. Yes, indeed, the point is not to hinder the user from submitting a new review. Only one review for each user, and if he wants to change his review, he can do so without adding a new review, because if he makes a good review and then adds a bad review, this is illogical.  As for local storage, the intention is that reviews should be part of the status of service cards, so I will not need, as you said, to enter additional local storage.

2024-01-10 13:56 UTC, doemser requested changes

2024-01-10 13:56 UTC, doemser commented on components/ReviewForm/index.js
> +  background-color: ${(props) => props.reviewButtonColor || "#2ecc71"};
why you hardcode a color alternative here?

2024-01-10 13:56 UTC, doemser commented on components/ReviewForm/index.js
> +    />
every input should have a label.
Placeholders are not enough to label your inputs as they:
- Disappear on focus
- Are often hard to read because of low contrast
- Are possibly not properly managed by screen readers

2024-01-10 13:56 UTC, doemser commented on components/ServiceProvider/index.js
> +    const [reviews, setReviews] = useState({});
please check if you have auto-format on save with prettier and confirm to me.

2024-01-10 13:56 UTC, doemser commented on components/ServiceProvider/index.js
> +  }, [card.id]);
Instead of handling localStorage logic yourself, better use a library like the use-local-storage-state library we showed you.

2024-01-10 13:56 UTC, doemser commented on components/ServiceProvider/index.js
> +    localStorage.setItem(`reviews_${card.id}`, JSON.stringify(updatedReviews));
do not handle localStorage logic yourself.

2024-01-10 14:26 UTC, AmjedXKhattab commented on components/ReviewForm/index.js
> +  background-color: ${(props) => props.reviewButtonColor || "#2ecc71"};
@doemser 
In this part of code, a color alternative has been provided for the Submit Review Button to ensure that the button will have a default color of the reviewButtonColor value is not provided by props.

2024-01-10 14:47 UTC, AmjedXKhattab commented on components/ServiceProvider/index.js
> +    const [reviews, setReviews] = useState({});
@doemser  I checked have auto-format on save with prettier  and I wasn't using it, but I installed it now

2024-01-11 10:53 UTC, mbosselmann reviewed
Hi Team ServiceCircle,
just some nit-picking remarks from my side left. Nothing that hinders me in approving this PR, but please check my comments. :)

2024-01-11 10:53 UTC, mbosselmann commented on components/ReviewForm/index.js
> +/>
Somehow the formatting of the code did not work here. The `input` should be on the same label as the `label`. 🤔

2024-01-11 10:53 UTC, mbosselmann commented on components/ServiceProvider/index.js
> +      const updatedCards = serviceCards.filter((c) => c.id !== card.id);
As you only need the id from the serviceCards array you could work with destructuring in this case:
`const updatedCards = serviceCards.filter(({id}) => id !== card.id);`

Would be much better as to use `c` as name for each item. :)

2024-01-11 10:53 UTC, mbosselmann commented on components/ServiceProvider/index.js
> +          <br />
A `br` element should not be used to create space between elements. It is used to create breaks in blocks of text. [See MDN](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/br#styling_with_css)

2024-01-11 10:53 UTC, mbosselmann commented on components/ServiceProvider/index.js
>              {showReviewForm ? "Hide Review Form" : "Add Review"}
I think "Add Review" is as text misleading if there already exists a review. I think the text then should be "Change Review" or something like that. Otherwise the user would think that it is possible to add another review. :)

2024-01-12 10:47 UTC, merged