UserAuthentification
Janis1992-08/Capstone-Project-ServiceCircle pull request #44
Opened 2024-01-15 15:10 UTC by Janis1992-08

2024-01-16 15:16 UTC, F-Kirchhoff requested changes
Hey!
your code looks great already, and quite complex too. Please try to reduce the repetition in your code, this will make your life much easier in the long run. Please take a look!

2024-01-16 15:16 UTC, F-Kirchhoff commented on components/AverageRating/index.js
> +  );
nice solution for rendering the stars ✨

2024-01-16 15:16 UTC, F-Kirchhoff commented on components/EditForm/index.js
> +    }
you should add the security for only editing providers by authenticated users in your api backend. This is not secure, since it can be easily circumvented.

2024-01-16 15:16 UTC, F-Kirchhoff commented on components/EditForm/index.js
> +    }
And you are returning JSX inside an event handler? This looks like a mistake.

2024-01-16 15:16 UTC, F-Kirchhoff commented on pages/_app.js
> +          <SwitchLabel onClick={toggleTheme}>
you don't need an onClick on the label, if they are connected with the checkbox via. "htmlFor" and with an "id" on the input.

2024-01-16 15:16 UTC, F-Kirchhoff commented on pages/index.js
>        <ul style={{ listStyleType: "none", padding: 0, margin: 0 }}>
please don't use inline-styling. create a styled component instead.

2024-01-16 15:16 UTC, F-Kirchhoff commented on pages/favorites/index.js
> +
I would highly reccomend to create a generic "ProtectedRoute" component, that you wrap your page content with. This Route Component checks if the user is authenticated and if not returns this access denied message. It may look something like this: 

```
function ProtectedRoute({fallback,children}) {
  const {status} = useSession()
  
  if(!status === 'authenticated') {
    return fallback // or redirect to login page with router.push()
  } 
  
  return <>{children}</>
}
```

2024-01-16 16:07 UTC, Janis1992-08 commented on components/EditForm/index.js
> +    }
oh yes, forgot to take it out.

2024-01-16 16:10 UTC, Janis1992-08 commented on pages/index.js
>        <ul style={{ listStyleType: "none", padding: 0, margin: 0 }}>
Got it. We are going to refactor/restyle in another user story.

2024-01-16 16:10 UTC, Janis1992-08 commented on pages/favorites/index.js
> +
Got it. I will give it a try.

2024-01-17 09:29 UTC, mbosselmann reviewed
Hi Team ServiceCircle,
LGTM! 🦊 
Only one remark is left. Please adjust the code accordingly, but I will approve this PR. :)

2024-01-17 09:29 UTC, mbosselmann commented on pages/api/providers/[id].js
>        await Provider.findByIdAndUpdate(id, updatedProvider, {
For `pages/api/providers/index.js` you added a session check by using `getServerSession` that should also be implemeted here for PUT, POST and DELETE too. Then you also check in your backend that only a logged in user can do this. (this is what Felix meant in his first remark). :)

2024-01-17 13:08 UTC, merged